### ISSUE TITLE
预训练模型sptm中的use_queue含义没太懂

### ISSUE THREAD

**Issue by wyqnumber** [wuba/qa_match#10]
if not args.use_queue:     
             utils.to_ids(training_sens, word2id, args, id2word)

另外，掩码方式没有使用实体词语进行MASK，只是使用了单字进行MASK？

**Comment by henryalps** [comment]
1.`use_queue`会影响样本的生成方式：
若设置`use_queue`为0，相当于无放回抽样，即每个epoche开始时对全部数据做shuffle并MASK，然后依次从MASK结果中抽取得到各个batches的数据；
若设置`use_queue`为1，相当于有放回抽样，即在生成每个样本时，都是从全部数据中随机抽取并MASK。前者相对后者速度明显更快，但损失了一定的随机性。
实验未发现设为1带来显著优化，且设为1会导致`train_step`参数失效，需要手动停止训练任务。因此一般配置为0即可。

2.该项目中MASK的是单字，但MASK词语也是可以的：
具体MASK的是字还是词，取决于输入文件`pre_train_data`。如输入文件采用分词结果（即token为词语，token间以空格作为间隔），则MASK的是词；如采用的是分字结果，则MASK的是字。注意`vocab`中一般应包含`pre_train_data`中的所有token。

**Comment by henryalps** [comment]
> ```
> if not args.use_queue:     
>          utils.to_ids(training_sens, word2id, args, id2word)
> ```
> 
> 另外，掩码方式没有使用实体词语进行MASK，只是使用了单字进行MASK？

1.`use_queue`会影响样本的生成方式：
若设置`use_queue`为0，相当于无放回抽样，即每个epoche开始时对全部数据做shuffle并mask，之后依次从里边抽取得到各个batches的数据；
若设置`use_queue`为1，相当于有放回抽样，即在生成每个样本时，都是从全部数据中随机抽取并mask。前者相对后者速度明显更快，但损失了一定的随机性。
实验未发现设为1带来显著优化，且设为1会导致`train_step`参数失效，需要手动停止训练任务。因此一般配置为0即可。

2.具体mask的是字还是词，取决于输入文件`pre_train_data`。如输入文件采用分词结果（即token为词语，token间以空格作为间隔），则mask的是词；如采用的是分字结果，则mask的是字。注意`vocab`中一般应包含`pre_train_data`中的所有token。
