### ISSUE TITLE
如果标准问题非常多，例如十万标准问题，那么每次epoch，验证验证集非常慢。因为是十万类的分类问题。请问你们有用到十万标准问题的训练集吗？这么慢如何处理？

### ISSUE THREAD

**Issue by liuchenbaidu** [wuba/qa_match#11]
if (train_batch_step + 1) % FLAGS.eval_every == 0:
                # run_num = run_num + 1
                # if run_num % 2 == 0:
                #     break
                all_valid_acc_num = 0
                all_valid_num = 0
                valid_batches = data_help.valid_batch_iterator()
                for _, valid_batch_q in enumerate(valid_batches):
                    all_valid_num = all_valid_num + len(valid_batch_q)
                    valid_batch = (valid_batch_q, data_help.std_batch)
                    valid_prob = sess.run([dssm.prob_pre], feed_dict=feed_dict_builder(valid_batch, 1.0, dssm))
                    valid_acc_num, real_labels, _ = cal_predict_acc_num(valid_prob[0], valid_batch_q,
                                                                        data_help.id2label)
                    all_valid_acc_num = all_valid_acc_num + valid_acc_num
                current_acc = all_valid_acc_num * 1.0 / all_valid_num
这段验证验证集非常慢。
例如想利用LCMC数据集，把每一个标记为1句子对抽出一个作为标准集的一个类。那么类别非常多。

**Comment by wy200507030** [comment]
您提的问题非常好，离线训练时如果如果标准问题达到万级别甚至是十万级别，在验证时不需要把所有验证集都跑一遍，这里用验证集跑下acc的目的是为了取得在验证集上最好的model，要达到这个目的完全可以每次随机从验证集取一部分，然后计算acc，如果去到best acc就保存模型。训练结束后，取得最优的模型后，在最后离线评测时可以把所有的验证集/测试集跑一遍。目前我们线上标准问题还达不到10W级别。

**Comment by liuchenbaidu** [comment]
1.每次随机从验证集取一部分，这个一部分是不是需要有一定比例，这个比例是有什么办法确定吗？
2.其次在验证集抽样取的最好的模型是否就一定是最好的模型呢？

**Comment by wy200507030** [comment]
1.这个比例具体取多少，需要综合考虑精度和要求的训练速度，具体需要实际测下，比如十分之一，五分之一之类，需要看下取不同比例的耗时和最终训练获得的模型精度。
2.目前按照这种方式训练得到的模型只能说尽量取相对较好的，理想状态下训练足够充分，收敛的情况下，取到的模型是最优的，但这里所说的最优都是模型的表征尽量接近真实的数据分布。

**Comment by liuchenbaidu** [comment]
感谢回答。抽样不是一个完美的解决方案吧，总的说来就要取舍了，需要确定抽样的比例了来说明总的验证集的准确率。
如果标准问题非常多（十万，百万等，类似于商品推荐了例如上百万的商品的相似度），求query与全体标准问题的相似度，时间复杂度高。所以是不是可以按照训练的方式取正负样本来验证？这样是全体验证集都可以验证，负样本随机生成(简化版就用验证集生成)
