### ISSUE TITLE
理解为一个句子分类问题，为什么不用textCNN,简单效果也挺好，而是用比较复杂dssm？

### ISSUE THREAD

**Issue by liuchenbaidu** [wuba/qa_match#12]
1.请问一下模型最终的precsion ,recall,是多少呢？
2.可以理解为是一个分类模型，用途简单的textCNN,在短文本问题上效果速率都挺好，为什么采用比较复杂的dssm结构？
textCNN模型，输入句子直接可以获取句子类别。
dssm的优势还是主要用在召回相似的句子吧。

**Comment by henryalps** [comment]
> 1.请问一下模型最终的precsion ,recall,是多少呢？
> 2.可以理解为是一个分类模型，用途简单的textCNN,在短文本问题上效果速率都挺好，为什么采用比较复杂的dssm结构？
> textCNN模型，输入句子直接可以获取句子类别。
> dssm的优势还是主要用在召回相似的句子吧。

1.precsion,recall见[RUNDEMO.md页面](https://github.com/wuba/qa_match/blob/master/docs/RUNDEMO.md#%E6%A8%A1%E5%9E%8B%E8%AF%84%E6%B5%8B%E6%8C%87%E6%A0%87%E5%8F%8A%E6%B5%8B%E8%AF%95%E9%9B%86%E6%95%88%E6%9E%9C)
2.您的想法非常有价值。
我们采用DSSM的原因是DSSM结构简单，通用性强，方便扩展。如样本类别增多，分类结构不适用时，可沿用DSSM结构进行文本匹配。事实上，DSSM中的LSTM可自由替换成CNN等结构，本项目只是提供一个思路示例，关于具体实现，您可以根据需求进一步定制。
