### ISSUE TITLE
dssm模型占用空间小,语料如果六七十万，模型会到170M多。

### ISSUE THREAD

**Issue by liuchenbaidu** [wuba/qa_match#15]
dssm模型占用空间小 这是优点，这个应该是跟语料有关，如果语料非常多，通过训练代码保存的最优模型，有170多兆，主要是
dssm_39653.data-00000-of-00001 文件比较大。是否保存的数据太多，有什么办法吗？

**Comment by liuchenbaidu** [comment]
原因是把embeding层维度加大了，准确率我看一层知识库只有0.8398，是否应该加入字向量，还有如果是用词作为词表，那么如果问句非常短时候容易出现oov的现象，不知道你们怎么处理？例如，好的，你好，行。

**Comment by henryalps** [comment]
> 原因是把embeding层维度加大了，准确率我看一层知识库只有0.8398，是否应该加入字向量，还有如果是用词作为词表，那么如果问句非常短时候容易出现oov的现象，不知道你们怎么处理？例如，好的，你好，行。

1. 模型文件大的原因是，模型中存储了所有标准问题的表示向量，在标准问题很多的时候，这个向量占据空间很大。您可以尝试调小embedding_size或者num_units两个参数，但这种做法会对效果有一定影响，需要权衡；
2.可以加入字向量，由于我们是用的字向量，且字典覆盖全面，所以没有出现oov的现象。

**Comment by liuchenbaidu** [comment]
1.是的，需要权衡。
2.如果只采用字向量，我达到的效果只有76%左右，你们用单纯用字向量效果很不错了。曾经做过单纯用字向量的分类，比用词向量效果差10个百分点，因为字的独立有意义还是比较弱的，单层模型难以学会分词这些内容。所以为啥你们可以达到百分之0.83？或者说觉得你们效果好的原因是什么？训练多少epoch?
