### ISSUE TITLE
如何使用公开的模型来测试效果？

### ISSUE THREAD

**Issue by threefoldo** [wuba/qa_match#6]
词典文件和所用的向量都没有提供，要测试的话，只能使用数字或者重头训练？

**Comment by wy200507030** [comment]
这里预训练模型提供了字典文件（data_demo中的vocab），意图识别和领域识别模型用的字典是在训练数据时自动生成的，并且在保存模型的时候在模型文件中生成了（model_merge中的model_min的min_vocab2id和model_max的vocab_max），这里为了不泄露数据我们对训练、验证、测试文本进行了加密。如果想要在实际场景用并且测试效果的话，建议用实际应用场景数据训练模型并测试具体场景效果，如果只想测效果并不是实际应用在具体业务的话，可以用我们提供的数据，按照我们给出的示例demo跑一下。
