### ISSUE TITLE
models/dssm.py bilstm-dssm,为啥不用cdssm.lstm训练和推理速度都很慢

### ISSUE THREAD

**Issue by liuchenbaidu** [wuba/qa_match#8]
with tf.name_scope('rotate'):
            temp = tf.tile(self.qs_y_raw, [1, 1])  # [batch_size, num_lstm_units*2]
            self.qs_y = tf.tile(self.qs_y_raw, [1, 1])  # [batch_size, num_lstm_units*2]
            for i in range(negtive_size):
                rand = int((random.random() + i) * batch_size / negtive_size)
                if rand == 0:
                    rand = rand + 1
                rand_qs_y1 = tf.slice(temp, [rand, 0], [batch_size - rand, -1])  # [batch_size - rand, num_lstm_units*2]
                rand_qs_y2 = tf.slice(temp, [0, 0], [rand, -1])  # [rand, num_lstm_units*2]
                self.qs_y = tf.concat(axis=0, values=[self.qs_y, rand_qs_y1,
                                                      rand_qs_y2])  # [batch_size*(negtive_size+1), num_lstm_units*2]
1.请问这段代码的主要的作用是什么？
2.dssm.py实现的dssm的变种bilstm-dssm,为啥不用cdssm.lstm训练和推理速度都很慢。

**Comment by wy200507030** [comment]
1.您的问题很好，这段代码主要是为了构造负例，原始的一个batch中文本表征顺序不变代表正例（label的顺序是固定的），然后每反转一次相当于label和对应文本表征的顺序发生了变化，代表随机生成了一个负例，反转n次相当于对batch中每一个样本生成了n个负例，这里需要注意原始生成batch时，一是batch中每类label只能出现一次（否则反转生成负例时有一定概率把相同label对应的文本还是反转给了它，相当于把正例当成负例了），二是batch size要小于真实的label数量（如果大于的话相当于反转时会把相同label对应的其他样本当成负例了），这里可以参考utils/match_utils.py数据预处理中的实现。另外readme中tips也有说明。
2.您的想法很好，可以用cdssm，用cnn做dssm的表征只也能够学到一定的上下文信息（n-gram），当时用lstm+dssm，主要考虑到lstm能够加入一定的时序信息（虽然有一定长距离依赖的损失，但本身项目考虑是短文本匹配），另外训练和推理时bilstm表征确实比用一个简单的cnn表征要慢。目前线上推理是先计算出要匹配的文本对应的特征表征和query对应的tensor一起写到图里的，线上推理依赖tfserving，对query做一个特征表征然后跟图中保存的doc特征做下cos相似度计算耗时差不多5-8ms（2000+doc，线上环境），当然用简单结构的cnn做特征表征会更快

**Comment by liuchenbaidu** [comment]
> 1.您的问题很好，这段代码主要是为了构造负例，原始的一个batch中文本表征顺序不变代表正例（label的顺序是固定的），然后每反转一次相当于label和对应文本表征的顺序发生了变化，代表随机生成了一个负例，反转n次相当于对batch中每一个样本生成了n个负例，这里需要注意原始生成batch时，一是batch中每类label只能出现一次（否则反转生成负例时有一定概率把相同label对应的文本还是反转给了它，相当于把正例当成负例了），二是batch size要小于真实的label数量（如果大于的话相当于反转时会把相同label对应的其他样本当成负例了），这里可以参考utils/match_utils.py数据预处理中的实现。另外readme中tips也有说明。
> 2.您的想法很好，可以用cdssm，用cnn做dssm的表征也能够学到一定的上下文信息（n-gram），当时用lstm+dssm，主要考虑到lstm能够加入一定的时序信息（虽然有一定长距离依赖的损失，但本身项目考虑是短文本匹配），另外训练和推理时bilstm表征确实比用一个简单的cnn表征要慢。目前线上推理是计算出要匹配的文本对应的特征表征和query对应的tensor一起写到图里的，线上推理依赖tfserving，对query做一个特征表征然后跟图中保存的doc特征做下cos相似度计算耗时差不多5-8ms（2000+doc，线上环境），当然用简单结构的cnn做特征表征会更快

研读了代码，总结一下. utils/match_utils.py中把训练样本按照标准问题，做成了dict，通过标准问题每次取不同的标准问题，组成batch。负样本组合这个batch交叉组合负样本。

**Comment by liuchenbaidu** [comment]
但是如果标准问题非常多，例如十万标准问题，那么每次epoch，测试测试集非常慢。因为是十万类的分类问题。请问你们有用到十万标准问题的训练集吗？这么慢如何处理？
